version: '3'
services:
  wanglab-coder-workflowtemplate:
    build:
      context: .
      dockerfile: Dockerfile.coder
    container_name: wanglab-coder-workflowtemplate
    volumes:
      - ..:/config/workspace:rw
    ports:
    - "8443:8443"
    restart: unless-stopped
    deploy:
     resources:
       limits:
         memory: 16000M
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Pacific
      - PASSWORD=${LOGINPASSWORD:-PASSWORD}
    labels:
      - traefik.http.routers.backend.rule=Host(`test.wanglab.science`)