name: Test Workflow

on: 
  push:
  pull_request:
    
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        # Installing Nextflow
        curl -s https://get.nextflow.io | bash
        mv nextflow /usr/local/bin

        # Installing Conda
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        chmod +x Miniconda3-latest-Linux-x86_64.sh
        bash ./Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"
        conda init bash
        conda config --set always_yes yes --set changeps1 no
    - name: Test Workflow
      run: |
        make run